version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql-mazam-api
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: mazam
      MYSQL_USER: mazam
      MYSQL_PASSWORD: mazam
      MYSQL_ROOT_PASSWORD: mazam
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql_volume:/var/lib/mysql

  redis:
    container_name: redis-mazam-api
    image: redis:6-alpine
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379

  adonis_app:
    container_name: adonis_app-mazam
    restart: always
    depends_on:
      - mysql
      - redis
    build:
      context: ./bin/docker/adonis
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

volumes:
  mysql_volume:
  redis_volume:
